// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeddmxqcudzjdgaorfyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZGRteHFjdWR6amRnYW9yZnluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NjM4MzYsImV4cCI6MjA2NjEzOTgzNn0.t9G0lhbqZ0nVQ8wUfs3FaRM0AqcSQualRV35TjGjKCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);